apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: linter-pipeline
spec:
  workspaces:
    - name: pipeline-shared-data
      description: |
        This workspace will be used to share information between pipeline steps
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: https://github.com/upslopeio/lint-markdown-files
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: lint-repository
      taskRef:
        name: markdown-lint
      runAfter:
        - clone-repository
      workspaces:
        - name: shared-workspace
          workspace: pipeline-shared-data
      params:
        - name: args
          value: ["."]
